name: SafetyCheck

on: 
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:
  python-safety-test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out master
        uses: actions/checkout@master

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master