name: SafetyCheck

on: 
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

env:
  DEP_PATH: src/requirements.txt

jobs:
  python-safety-test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out main
        uses: actions/checkout@main

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@main